'use client'

import { useState, useEffect, useRef } from 'react'
import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { supabase } from '@/lib/supabase'
import { toast } from 'react-hot-toast'
import { useRouter } from 'next/navigation'
import { trackActivity } from '@/lib/activity-tracking'
import { AlertCircle, CheckCircle2, Calendar, Clock, UtensilsCrossed } from 'lucide-react'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'

interface PlanDay {
  day: string
  breakfast: string
  '12pm': string
  lunch: string
  '6pm': string
  dinner: string
}

interface Plan {
  id: string
  user_id: string
  plan_type: 'sample' | 'ai'
  prakriti: string
  start_date: string
  end_date: string
  is_active: boolean
  summary: string
  payload: PlanDay[]
  created_at: string
}

interface MealLoggingProps {
  userId: string
}

interface UserPrakriti {
  prakriti: string | null
  hasOnboarding: boolean | undefined // undefined = unknown (error occurred), false = confirmed no onboarding, true = confirmed has onboarding
}

export function MealLogging({ userId }: MealLoggingProps) {
  const [plan, setPlan] = useState<Plan | null>(null)
  const [userPrakriti, setUserPrakriti] = useState<UserPrakriti>({ prakriti: null, hasOnboarding: false })
  const [loading, setLoading] = useState(true)
  const [applyingPlan, setApplyingPlan] = useState(false)
  const [generatingPlan, setGeneratingPlan] = useState(false)
  const [selectedDay, setSelectedDay] = useState<string | null>(null)
  const [allergies, setAllergies] = useState<string[]>([])
  const [autoGenerating, setAutoGenerating] = useState(false)
  const hasAutoGeneratedRef = React.useRef(false)
  const router = useRouter()

  useEffect(() => {
    loadData()
  }, [userId])

  const loadData = async () => {
    setLoading(true)
    try {
      // Load user prakriti and get the actual value
      let loadedPrakriti: string | null = null
      let hasOnboardingData = false
      
      // First, check if onboarding exists using a simple query
      // Use select('id') first to avoid column-specific errors
      const { data: onboardingExists, error: existsError } = await supabase
        .from('onboarding')
        .select('id')
        .eq('user_id', userId)
        .maybeSingle()
      
      if (existsError) {
        // Check error type
        if (existsError.code === 'PGRST116' || existsError.message?.includes('No rows')) {
          // Confirmed: no onboarding exists
          hasOnboardingData = false
        } else {
          // Real error (400/406) - might be RLS/schema issue
          // User might have onboarding but we can't access it
          // Assume they have it to avoid false "Complete Assessment" message
          console.warn('Error checking onboarding (assuming user might have it):', existsError)
          hasOnboardingData = true // Assume they have it
        }
      } else if (onboardingExists) {
        // Onboarding exists - get prakriti data
        hasOnboardingData = true
        
        // Try to get prakriti from onboarding
        const { data: onboardingData, error: dataError } = await supabase
          .from('onboarding')
          .select('dominant_dosha, prakriti_summary, prakriti')
          .eq('user_id', userId)
          .maybeSingle()
        
        if (!dataError && onboardingData) {
          loadedPrakriti = onboardingData.dominant_dosha || onboardingData.prakriti_summary?.dominant || onboardingData.prakriti || null
        } else if (dataError && dataError.code !== 'PGRST116') {
          console.warn('Onboarding exists but error getting prakriti:', dataError)
          // Onboarding exists but we can't get prakriti - that's OK, hasOnboardingData is already true
        }
      } else {
        // No onboarding found
        hasOnboardingData = false
      }
      
      // Try user_profiles prakriti column (if migration was run)
      if (!loadedPrakriti) {
        const { data: profile, error: profileError } = await supabase
          .from('user_profiles')
          .select('prakriti')
          .eq('id', userId)
          .maybeSingle()

        // Ignore errors if column doesn't exist (400 error)
        if (!profileError && profile?.prakriti) {
          loadedPrakriti = profile.prakriti
          if (!hasOnboardingData) {
            hasOnboardingData = true // If we found prakriti in profile, user has onboarding
          }
        }
      }
      
      // Update state
      setUserPrakriti({ 
        prakriti: loadedPrakriti, 
        hasOnboarding: hasOnboardingData 
      })
      
      // Load current plan
      const planResponse = await fetch(`/api/plans/current?user_id=${userId}`)
      let loadedPlan: Plan | null = null
      
      if (planResponse.ok) {
        const planData = await planResponse.json()
        loadedPlan = planData.plan || null
        setPlan(loadedPlan)
        
        // Set selected day if plan exists
        if (loadedPlan?.payload && loadedPlan.payload.length > 0) {
          const today = new Date().toLocaleDateString('en-US', { weekday: 'long' }).toUpperCase()
          const dayExists = loadedPlan.payload.find((d: PlanDay) => d.day === today)
          setSelectedDay(dayExists ? today : loadedPlan.payload[0].day)
        }
      } else {
        setPlan(null)
      }
      
      // Load allergies from investigation
      await loadAllergies()
      
      // Auto-generate plan if needed (after all data is loaded)
      // Check if user has prakriti but no plan (first visit)
      if (
        !hasAutoGeneratedRef.current &&
        loadedPrakriti &&
        !loadedPlan &&
        hasOnboardingData
      ) {
        hasAutoGeneratedRef.current = true
        setAutoGenerating(true)
        try {
          await autoGeneratePlan()
          // Reload plan after generation
          const reloadResponse = await fetch(`/api/plans/current?user_id=${userId}`)
          if (reloadResponse.ok) {
            const reloadData = await reloadResponse.json()
            if (reloadData.plan) {
              setPlan(reloadData.plan)
              if (reloadData.plan.payload && reloadData.plan.payload.length > 0) {
                const today = new Date().toLocaleDateString('en-US', { weekday: 'long' }).toUpperCase()
                const dayExists = reloadData.plan.payload.find((d: PlanDay) => d.day === today)
                setSelectedDay(dayExists ? today : reloadData.plan.payload[0].day)
              }
            }
          }
        } catch (error) {
          console.error('Auto-generation failed:', error)
          hasAutoGeneratedRef.current = false // Allow manual retry
        } finally {
          setAutoGenerating(false)
        }
      }
    } catch (error) {
      console.error('Error loading data:', error)
      toast.error('Failed to load meal plan data')
    } finally {
      setLoading(false)
    }
  }

  // These functions are kept for backward compatibility but main logic is in loadData
  const loadUserPrakriti = async () => {
    // Logic moved to loadData for better state management
  }

  const loadCurrentPlan = async () => {
    // Logic moved to loadData for better state management
  }

  const loadAllergies = async () => {
    try {
      const { data: onboarding, error } = await supabase
        .from('onboarding')
        .select('investigation')
        .eq('user_id', userId)
        .maybeSingle()

      if (error) {
        console.warn('Error loading allergies:', error)
        return
      }

      if (onboarding?.investigation?.medical_history?.allergies) {
        const allergyText = onboarding.investigation.medical_history.allergies
        // Simple parsing - split by comma or newline
        const allergyList = allergyText.split(/[,\n]/).map(a => a.trim().toLowerCase()).filter(Boolean)
        setAllergies(allergyList)
      }
    } catch (error) {
      console.error('Error loading allergies:', error)
    }
  }

  const autoGeneratePlan = async () => {
    try {
      console.log('Auto-generating sample plan for user:', userId)
      
      // Prefer sample plan for auto-generation (faster, more reliable)
      const response = await fetch('/api/plans/apply-sample', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: userId })
      })

      const data = await response.json()

      if (!response.ok) {
        console.warn('Auto-generation failed, user can manually apply:', data.error)
        // Don't show error toast for auto-generation failures - user can manually apply
        hasAutoGeneratedRef.current = false // Allow retry
        return
      }

      console.log('Auto-generated plan successfully')
      // Reload plan to show it
      await loadCurrentPlan()
    } catch (error) {
      console.error('Error auto-generating plan:', error)
      // Silent fail - user can manually apply
      hasAutoGeneratedRef.current = false // Allow retry
    }
  }

  const handleApplySamplePlan = async () => {
    setApplyingPlan(true)
    try {
      await trackActivity(userId, 'apply_sample_plan_click')
      
      const response = await fetch('/api/plans/apply-sample', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: userId })
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || 'Failed to apply sample plan')
      }

      toast.success('Sample plan applied successfully!')
      await loadCurrentPlan()
    } catch (error: any) {
      console.error('Error applying sample plan:', error)
      toast.error(error.message || 'Failed to apply sample plan')
    } finally {
      setApplyingPlan(false)
    }
  }

  const handleGenerateAIPlan = async () => {
    setGeneratingPlan(true)
    try {
      await trackActivity(userId, 'generate_ai_plan_click')
      
      const response = await fetch('/api/plans/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: userId })
      })

      const data = await response.json()

      if (!response.ok) {
        // Handle specific error codes
        if (data.code === 'NO_ONBOARDING') {
          toast.error('Please complete your onboarding first', { duration: 5000 })
          router.push('/onboarding')
          return
        } else if (data.code === 'NO_PRAKRITI') {
          toast.error('Please complete your Prakriti assessment first', { duration: 5000 })
          router.push('/onboarding')
          return
        }
        throw new Error(data.error || data.details || 'Failed to generate plan')
      }

      toast.success('AI plan generated successfully!')
      await loadCurrentPlan()
    } catch (error: any) {
      console.error('Error generating plan:', error)
      toast.error(error.message || 'Failed to generate plan')
    } finally {
      setGeneratingPlan(false)
    }
  }

  const handleMarkMealEaten = async (day: string, mealSlot: string, menuText: string) => {
    try {
      const response = await fetch('/api/meals/log', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          user_id: userId,
          plan_id: plan?.id,
          date: new Date().toISOString().split('T')[0],
          meal_slot: mealSlot === '12pm' ? 'snack12' : mealSlot === '6pm' ? 'snack6' : mealSlot,
          menu_text: menuText,
          source: 'plan',
          created_via: 'meal_logging_ui'
        })
      })

      if (!response.ok) {
        throw new Error('Failed to log meal')
      }

      toast.success('Meal marked as eaten!')
      await trackActivity(userId, 'meal_marked_eaten')
    } catch (error) {
      console.error('Error marking meal:', error)
      toast.error('Failed to mark meal as eaten')
    }
  }

  const checkAllergyConflict = (mealText: string): string | null => {
    if (allergies.length === 0) return null
    
    const normalizedMeal = mealText.toLowerCase()
    const conflict = allergies.find(allergy => normalizedMeal.includes(allergy))
    return conflict || null
  }

  // Loading state or auto-generating
  if (loading || autoGenerating) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold mb-2">Meal Logging</h1>
          <p className="text-muted-foreground">
            {autoGenerating ? 'Generating your personalized meal plan...' : 'Loading...'}
          </p>
        </div>
        <div className="h-8 bg-muted animate-pulse rounded" />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map(i => (
            <Card key={i} className="h-64 animate-pulse" />
          ))}
        </div>
      </div>
    )
  }

  // No prakriti - show CTA to complete assessment
  // Only show this if we're CERTAIN there's no onboarding (not just an error)
  // hasOnboarding === false means we confirmed no onboarding exists
  // hasOnboarding === undefined means we had an error and don't know - don't show this message
  if (userPrakriti.hasOnboarding === false && !userPrakriti.prakriti) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold mb-2">Meal Logging</h1>
          <p className="text-muted-foreground">
            Track your meals from your personalized diet plan
          </p>
        </div>
        
        <Alert>
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            <div className="space-y-4">
              <p className="font-semibold">Complete your Prakriti Assessment to generate a personalized diet plan</p>
              <p className="text-sm text-muted-foreground">
                Your meal plan will be customized based on your unique Ayurvedic constitution (Prakriti).
              </p>
              <Button 
                onClick={() => router.push('/onboarding')}
                className="mt-2"
              >
                Go to Prakriti Assessment
              </Button>
            </div>
          </AlertDescription>
        </Alert>
      </div>
    )
  }

  // Has prakriti but no plan - show CTA to apply sample plan
  // Also show if we have onboarding but couldn't determine prakriti (might be schema issue)
  // Don't show if we're uncertain about onboarding status
  if (!plan && (userPrakriti.prakriti || userPrakriti.hasOnboarding === true)) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold mb-2">Meal Logging</h1>
          <p className="text-muted-foreground">
            Track your meals from your personalized diet plan
          </p>
        </div>
        
        <Card className="border-primary/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <UtensilsCrossed className="h-5 w-5 text-primary" />
              Apply Your {userPrakriti.prakriti ? (userPrakriti.prakriti.charAt(0).toUpperCase() + userPrakriti.prakriti.slice(1)) : 'Personalized'} Diet Plan
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              You have completed your Prakriti assessment. Apply a 7-day sample plan{userPrakriti.prakriti ? ` based on your ${userPrakriti.prakriti} constitution` : ''}, 
              or generate a custom AI-powered 15-day plan.
            </p>
            <div className="flex flex-col sm:flex-row gap-3">
              <Button 
                onClick={handleApplySamplePlan}
                disabled={applyingPlan}
                className="flex-1"
              >
                {applyingPlan ? 'Applying...' : 'Apply 7-Day Sample Plan'}
              </Button>
              <Button 
                onClick={handleGenerateAIPlan}
                disabled={generatingPlan}
                variant="outline"
                className="flex-1"
              >
                {generatingPlan ? 'Generating...' : 'Generate AI Plan (15 Days)'}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              Sample plans are based on canonical Ayurvedic meal plans. AI plans are personalized based on your investigation data.
            </p>
          </CardContent>
        </Card>
      </div>
    )
  }

  // Has plan - show meal plan
  const currentDay = plan.payload.find((d: PlanDay) => d.day === selectedDay) || plan.payload[0]
  const daysOfWeek = plan.payload.map((d: PlanDay) => d.day)

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold mb-2">Your Meal Plan</h1>
          <p className="text-muted-foreground">
            {plan.plan_type === 'sample' ? '7-day' : '15-day'} {plan.prakriti} plan
          </p>
        </div>
        <div className="flex gap-2">
          <Button 
            onClick={handleGenerateAIPlan}
            disabled={generatingPlan}
            variant="outline"
            size="sm"
          >
            {generatingPlan ? 'Generating...' : 'Regenerate Plan (AI)'}
          </Button>
        </div>
      </div>

      {/* Plan Metadata */}
      <Card className="bg-primary/5 border-primary/20">
        <CardContent className="p-4">
          <div className="flex flex-wrap items-center gap-4 text-sm">
            <div className="flex items-center gap-2">
              <Badge variant={plan.plan_type === 'sample' ? 'default' : 'secondary'}>
                {plan.plan_type === 'sample' ? 'Sample Plan' : 'AI Generated'}
              </Badge>
              <span className="text-muted-foreground">
                {plan.prakriti ? (plan.prakriti.charAt(0).toUpperCase() + plan.prakriti.slice(1)) : 'Personalized'} Plan
              </span>
            </div>
            <div className="flex items-center gap-2 text-muted-foreground">
              <Calendar className="h-4 w-4" />
              <span>
                {new Date(plan.start_date).toLocaleDateString()} - {new Date(plan.end_date).toLocaleDateString()}
              </span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Day Selector */}
      <div className="flex flex-wrap gap-2">
        {daysOfWeek.map((day: string) => (
          <Button
            key={day}
            variant={selectedDay === day ? 'default' : 'outline'}
            size="sm"
            onClick={() => setSelectedDay(day)}
          >
            {day}
          </Button>
        ))}
      </div>

      {/* Current Day Meals */}
      {currentDay && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[
            { slot: 'breakfast', label: 'Breakfast', icon: '🌅' },
            { slot: '12pm', label: '12 PM Snack', icon: '🍎' },
            { slot: 'lunch', label: 'Lunch', icon: '🍽️' },
            { slot: '6pm', label: '6 PM Snack', icon: '🥜' },
            { slot: 'dinner', label: 'Dinner', icon: '🌙' }
          ].map(({ slot, label, icon }) => {
            const mealText = currentDay[slot as keyof PlanDay] as string
            if (!mealText) return null
            
            const allergyConflict = checkAllergyConflict(mealText)
            const mealSlot = slot === '12pm' ? 'snack12' : slot === '6pm' ? 'snack6' : slot

            return (
              <Card 
                key={slot} 
                className={`${allergyConflict ? 'border-warning bg-warning/5' : ''}`}
              >
                <CardHeader>
                  <CardTitle className="text-base flex items-center justify-between">
                    <span className="flex items-center gap-2">
                      <span>{icon}</span>
                      {label}
                    </span>
                    {allergyConflict && (
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger>
                            <AlertCircle className="h-4 w-4 text-warning" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p>Check with doctor: contains {allergyConflict}</p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    )}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <p className={`text-sm ${allergyConflict ? 'text-muted-foreground line-through' : ''}`}>
                    {mealText}
                  </p>
                  <div className="flex items-center justify-between">
                    <Badge variant="outline" className="text-xs">
                      From SwasthPrameh {plan.prakriti ? (plan.prakriti.charAt(0).toUpperCase() + plan.prakriti.slice(1)) : 'Personalized'} Plan
                    </Badge>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => handleMarkMealEaten(selectedDay || '', mealSlot, mealText)}
                      className="h-7 text-xs"
                    >
                      <CheckCircle2 className="h-3 w-3 mr-1" />
                      Mark Eaten
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}
